; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -mtriple=powerpc64le-unknown-linux-gnu \
; RUN:   -mcpu=pwr9 < %s | FileCheck %s
; RUN: llc -verify-machineinstrs -mtriple=powerpc64-unknown-linux-gnu \
; RUN:   -mcpu=pwr9 < %s | FileCheck %s
; RUN: llc -verify-machineinstrs -mtriple=powerpc-unknown-aix \
; RUN:   -mcpu=pwr9 < %s | FileCheck %s
; RUN: llc -verify-machineinstrs -mtriple=powerpc64-unknown-aix \
; RUN:   -mcpu=pwr9 < %s | FileCheck %s

declare void @llvm.ppc.stfiw(i8*, double)
define dso_local void @test_stfiw(i32* %cia, double %da) {
; CHECK-LABEL: test_stfiw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    stxsiwx 1, 0, 3
; CHECK-NEXT:    blr
entry:
  %0 = bitcast i32* %cia to i8*
  tail call void @llvm.ppc.stfiw(i8* %0, double %da)
  ret void
}

define dso_local void @test_xl_stfiw(i32* %cia, double %da) {
; CHECK-LABEL: test_xl_stfiw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    stxsiwx 1, 0, 3
; CHECK-NEXT:    blr
entry:
  %0 = bitcast i32* %cia to i8*
  tail call void @llvm.ppc.stfiw(i8* %0, double %da)
  ret void
}
